[[runs]]
######
# GA #
######
pop_size = 100
ea_steps = 2
mut_prob = 0.4
num_genes = 8
num_bind_sites = 2
#GA will terminate when best fitness drops below this value
fitness_term_threshold = 0.0
bind_threshold = 0.1
prod_rate_incr = 0.1

######################
# Regulatory Simulation #
######################
reg_steps = 50
min_protein_threshold = 0.04

decay_rate = 0.05
#note: if the number of unique proteins is less than num_initial_proteins, it will be used instead
num_initial_proteins = 4
max_proteins = 20
max_mut_float_change = 0.5
max_mut_bits_change = 8
binding_seq_play = 0

###############################
# Genotype -> Phenotype Mapping #
###############################
# note: bounds are inclusive
dev_start_iter = 10
cell_div_conc_threshold = 0.25

initial_cell_energy = 5.0

##########################
#Random Number Generation #
##########################
fix_rng_seed = false
rng_seed = 1207586232