[[runs]]
######
# GA #
######
pop_size = 15
ea_steps = 4
point_mut_prob = 0.1
dup_mut_prob = 0.5
sys_level_mut_prob = 0.5
num_initial_genes = 1
max_genes = 10

tourn_size = 3

#GA will terminate when best fitness drops below this value
fitness_term_threshold = 0.0

#if the gene score (# of times the gene produces)
#is above this threshold, the gene will be duplicated when mutation happens
gene_dup_count_threshold = 3
gene_sys_level_threshold = 3
gene_dup_gen_limit = 10
gene_sys_level_gen_limit = 10

#########################
# Regulatory Simulation #
#########################
reg_steps = 50

#proteins are deleted when all conc values are below this threshold
protein_deletion_threshold = 0.04

max_prod_rate = 0.75

decay_rate = 0.01

#note: actual number of initial proteins may be less than this (they must be unique)
num_initial_proteins = 5

initial_cell_sensor_conc = 0.75

#proteins will stop being produced when this count is exceeded
max_proteins_per_cell = 50

diff_alpha = 0.25
diff_h = 1.0
diff_dt = 1.0

#weight given to accuracy in fitness fcn
initial_acc_weight = 0.5
#weight given to evolvability in fitness fcn
initial_ev_weight = 0.5
#amount the weight shifts (evolvability -> accuracy) on each ea_step
weight_shift = 0.02
#weight shift will stop when accuarcy weight gets to this value
max_acc_weight = 1.0
min_ev_weight = 0.0

#note: number of production sites = number of bind sites
bind_sites_per_gene = 1

#################################
# Genotype -> Phenotype Mapping #
#################################
#cells will stop dividing when they meet or exceed this limit
division_age_limit = 40

#cells can only divide when the (application) division protein exceeds this threshold
cell_division_threshold = 0.2

#maximum number of children per cell (i.e. max airity of functions)
max_children = 2
max_tree_size = 7

#max conc value for sensor proteins (controls how much neighbour protein can be transferred between cells)
max_sensor_amount = 0.75
#cell sensors can only be reinforced when the (application) sensor protein exceeds this threshold
sensor_reinforcement_threshold = 0.2
#cell symbol probs can only be changed when the (application) sym protein exceeds this threshold
sym_prob_threshold = 0.2

max_protein_arg = 255 #must be in range [max(max_children, num_symbols), 2^8 - 1=255]

###########################
#Random Number Generation #
###########################
fix_rng_seed = false
user_rng_seed = 2504327168

############
# Tracking #
############
#0 = nothing
#1 = fitnesses
#2 = fitnesses & indivs
log_level = 2
step_range = "0:1:4"
#filename (path is specified in RunMod.jl)
data_output_file = "data"
multithreaded = true
#value may be set to any key from CompressionMod.routing_dict
compression_alg = "codecxz"

#CodecZlib: 151 MB
#CodecXz: 145 MB
#Checkpoint compression and CodecXz: 31 MB, 13:42
#Checkpoint compression and Blosc compression: 90 MB, 7:31 **
#Checkpoint compression and CodecZlib (Gzip): 256 MB, 7:36
#Checkpoint compression and CodecBzip2: 316 MB, 11:19
#Checkpoint compression and CodecZstd: 260 MB, 7:24

